// Generated by tools/generate_native_studio_model_catalog.py. Do not edit.
#pragma once

#include "model_catalog.h"

#include <array>

namespace gem16::studio::generated {

inline constexpr std::array kGemma4Unified12BTargetFiles{
    ModelCatalogFile{".gitattributes", 1570ULL, "34448b82c17d60fec9b65b1f093c115ddbaadc04beb1b0140b6bfed2e012a930", "52373fe24473b1aa44333d318f578ae6bf04b49b", "unsloth/gemma-4-12b-it-NVFP4", "b1f649734b34aa5575b03d186abd1b9be3d0d5c4", ".gitattributes"},
    ModelCatalogFile{"README.md", 29820ULL, "9e2712c56330ea7eefc00a10fd3c37a63364b92e52f10e12266b01a3dc6a9887", "f43dcf66ea657ff11cc683e53122b219bce2e8df", "unsloth/gemma-4-12b-it-NVFP4", "b1f649734b34aa5575b03d186abd1b9be3d0d5c4", "README.md"},
    ModelCatalogFile{"chat_template.jinja", 18924ULL, "845f1ee48e39fc942fe190da9df6a1c5db229e17a96ea08966ad1c9274e73d1b", "e929d662bbbf430219c28133472e0956733a8f84", "unsloth/gemma-4-12b-it-NVFP4", "b1f649734b34aa5575b03d186abd1b9be3d0d5c4", "chat_template.jinja"},
    ModelCatalogFile{"config.json", 7292ULL, "bcc0ec0398a9dd0b09586f835f17c05ed2cce99d958dd59ef629ce77e618ee49", "895577e08537dbce788bdc7a9102bf85bea2e91f", "unsloth/gemma-4-12b-it-NVFP4", "b1f649734b34aa5575b03d186abd1b9be3d0d5c4", "config.json"},
    ModelCatalogFile{"generation_config.json", 255ULL, "801ecff5b38d5a5f5072cd1fb0ee03afabed577fb754518266fea69453acfe6b", "b052ccdb6a742edb72bc98d7d7dd02f0c58e4680", "unsloth/gemma-4-12b-it-NVFP4", "b1f649734b34aa5575b03d186abd1b9be3d0d5c4", "generation_config.json"},
    ModelCatalogFile{"model.safetensors", 9304966064ULL, "7c2ee23298e7c3a9247e8947597dca5a38f8b791a0322487466d2bfad8ce704b", "7c2ee23298e7c3a9247e8947597dca5a38f8b791a0322487466d2bfad8ce704b", "unsloth/gemma-4-12b-it-NVFP4", "b1f649734b34aa5575b03d186abd1b9be3d0d5c4", "model.safetensors"},
    ModelCatalogFile{"processor_config.json", 1382ULL, "6b938e76555b3e9946890770e1abcd442a4718f34041a58e8139dc8ad34545c9", "b889adcd78015bf5a0139438c5fb0b7067529a61", "unsloth/gemma-4-12b-it-NVFP4", "b1f649734b34aa5575b03d186abd1b9be3d0d5c4", "processor_config.json"},
    ModelCatalogFile{"recipe.yaml", 661ULL, "bb19ac4f3bf8c4ffb9b88701bef8faf06c679ae9461751cc849375bb1731c17b", "c27417aceaf0637177e9d44c48ea59ccef873503", "unsloth/gemma-4-12b-it-NVFP4", "b1f649734b34aa5575b03d186abd1b9be3d0d5c4", "recipe.yaml"},
    ModelCatalogFile{"tokenizer.json", 32169726ULL, "adbaa8175acf7609b4359724f40eff359ec4fac1a8647eeb99d4422be708e1cf", "adbaa8175acf7609b4359724f40eff359ec4fac1a8647eeb99d4422be708e1cf", "unsloth/gemma-4-12b-it-NVFP4", "b1f649734b34aa5575b03d186abd1b9be3d0d5c4", "tokenizer.json"},
    ModelCatalogFile{"tokenizer_config.json", 3089ULL, "a62f4e85a47c0c136edaaa3a4f591fd6783717299a9def47e5ad03a49f6a5eb9", "6520cdc25462a5eba96fdac6d8cf3caa461feb35", "google/gemma-4-12B-it", "707f0a3b8a3c7ad586ed01e27eafbad8a27dd0f7", "tokenizer_config.json"},
};
inline constexpr ModelComponentCatalog kGemma4Unified12BTarget{
    "gemma4-12b-target", "12B Target", "unsloth/gemma-4-12b-it-NVFP4",
    "b1f649734b34aa5575b03d186abd1b9be3d0d5c4", kGemma4Unified12BTargetFiles, true,
    ""};

inline constexpr std::array kGemma4Unified12BAssistantFiles{
    ModelCatalogFile{".gitattributes", 1624ULL, "484fac0cb8b057eefe1992c8b72ac6e7438c7d17bd60c0e278b401c2190f7e72", "602d20f6eefed4b62821062891a7a495e25435f9", "google/gemma-4-12B-it-assistant", "364bd03c9952e5b7da73665ee30c9eccfc408345", ".gitattributes"},
    ModelCatalogFile{"README.md", 29899ULL, "eb9c31937729ee1da6767900f2d3ee79e72f070fdb0181b68983df742abc97d8", "d4d487c449ba880eda5b75718a36a2b65b7ac65b", "google/gemma-4-12B-it-assistant", "364bd03c9952e5b7da73665ee30c9eccfc408345", "README.md"},
    ModelCatalogFile{"config.json", 2346ULL, "b6f19209588fcefe41f65b193fad6148446253c470d36e29441ecc5158a54e6d", "9889070ccf194bd3cab6f61954218a4058696537", "google/gemma-4-12B-it-assistant", "364bd03c9952e5b7da73665ee30c9eccfc408345", "config.json"},
    ModelCatalogFile{"generation_config.json", 233ULL, "02b56bd11e1cd1e363e701a85a2fd7fbaa2992ec3358c1cd7cc44ead7208f505", "6e4ef65e8cf563a9177fd933423f89eed2f74d74", "google/gemma-4-12B-it-assistant", "364bd03c9952e5b7da73665ee30c9eccfc408345", "generation_config.json"},
    ModelCatalogFile{"model.safetensors", 845719296ULL, "3279c173daddd7186e79d652ad94022415736d3a1370625696c898429b06d6df", "3279c173daddd7186e79d652ad94022415736d3a1370625696c898429b06d6df", "google/gemma-4-12B-it-assistant", "364bd03c9952e5b7da73665ee30c9eccfc408345", "model.safetensors"},
    ModelCatalogFile{"tokenizer.json", 32169884ULL, "c001d9ada50af662c94f5ab17ec7e09f6438d1bec8246c47fee6510693d8de35", "c001d9ada50af662c94f5ab17ec7e09f6438d1bec8246c47fee6510693d8de35", "google/gemma-4-12B-it-assistant", "364bd03c9952e5b7da73665ee30c9eccfc408345", "tokenizer.json"},
    ModelCatalogFile{"tokenizer_config.json", 822ULL, "089594a3924fcfd4cb1c596a7906fbf476193519e5198f780912eed02b177e42", "1a6bee041ca75778c514a071efbdb568b0f3d7b0", "google/gemma-4-12B-it-assistant", "364bd03c9952e5b7da73665ee30c9eccfc408345", "tokenizer_config.json"},
};
inline constexpr ModelComponentCatalog kGemma4Unified12BAssistant{
    "gemma4-12b-assistant", "12B Assistant", "google/gemma-4-12B-it-assistant",
    "364bd03c9952e5b7da73665ee30c9eccfc408345", kGemma4Unified12BAssistantFiles, false,
    ""};

inline constexpr std::array kGemma4Moe26BA4BTargetFiles{
    ModelCatalogFile{".gitattributes", 187ULL, "2d502a6b780657021f7120758914e3ee67a36c538f02fe2040f29fe70569b9c9", "2d64a1552d229652d54397359f91c516b5ea089a", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", ".gitattributes"},
    ModelCatalogFile{"LICENSE", 634ULL, "e32c5cdb30142b7c670d61be0f2de18ab0007f72ef131e2869ef51687539c86d", "506ff98349a36c9b78904645c9ae492a9b62e826", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "LICENSE"},
    ModelCatalogFile{"NOTICE", 995ULL, "db1f7267dfe16a3887a73a47e5f04e222b39ba5415bce05900bd1d0fe34211a6", "d7d19d4435c2cf745e3465609e06c9b1327f518b", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "NOTICE"},
    ModelCatalogFile{"README.md", 32548ULL, "1f72b10109d89d5f3c893aca915ef8a0c30612df0b8a263c932f0e40e11cea9a", "f8c40dce335198f993a3da07b33b8c1102d223a2", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "README.md"},
    ModelCatalogFile{"chat_template.jinja", 18683ULL, "ae53464bf3be25802b3a5b37def7fd89667067d7577049b3b2d74c4d8de4c6d4", "4741bf6e4132ba23a5537f9d6e74e9a6d613d7cd", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "chat_template.jinja"},
    ModelCatalogFile{"config.json", 4152ULL, "8a647d5444c9e77b03bd80ac802683ffdbf64b3d9296ca5257ced8e50349ea16", "ef0ecec886c4ee7fb9151bbd2a4395973e96c061", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "config.json"},
    ModelCatalogFile{"gem16.lock.json", 4231ULL, "d7d2d30743e7c42aa55537a83f563047c9cbd2d83e0d583a2d2c8bcacbfa51a4", "d2f5aa90480db072e7b3258e16abca22e6bd93cf", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "gem16.lock.json"},
    ModelCatalogFile{"gem16_compilation.json", 3061406ULL, "7e5e78b9c6f61fbe8829866395634085261e1261a8c783f69affc5a16bd1847a", "fe671accce31db603d8d139bcef8523ee3baac34", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "gem16_compilation.json"},
    ModelCatalogFile{"gem16_components.json", 2535ULL, "d9bc235243b6cce80eac3999a608570b9bff4e46b4ef6f93781b74a63df1ee0b", "0108da968883cbee8221bcf05c0c8c91986cb43b", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "gem16_components.json"},
    ModelCatalogFile{"gem16_model.json", 671ULL, "c1015228120105ff5e54efe300c77c7e6a831ed598425f4f4c1b27c673732049", "02cf4afbfe3051e630eecd85c313fbb2a11ef015", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "gem16_model.json"},
    ModelCatalogFile{"generation_config.json", 203ULL, "b69207f9be617e982d13cc273cce6fd88c98dda99a4bdc5e2d52ffe0a0d9f0a9", "5a376e9fca28bfac73fe81b623bd6e4d00bb0817", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "generation_config.json"},
    ModelCatalogFile{"model.gem16", 14696668160ULL, "1ed73cf105b68db937ac0992283d31fdb2225474204341440721f41fe871bb72", "1ed73cf105b68db937ac0992283d31fdb2225474204341440721f41fe871bb72", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "model.gem16"},
    ModelCatalogFile{"tokenizer.json", 32169626ULL, "cc8d3a0ce36466ccc1278bf987df5f71db1719b9ca6b4118264f45cb627bfe0f", "cc8d3a0ce36466ccc1278bf987df5f71db1719b9ca6b4118264f45cb627bfe0f", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "tokenizer.json"},
    ModelCatalogFile{"tokenizer_config.json", 3729ULL, "3ab5c7b94dc97d65ca7064496fa69b88ff875378e1cb7ee3e43070c3a8170999", "bd297dce3d66737f7d6f9136691db3ad05991a2f", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "tokenizer_config.json"},
};
inline constexpr ModelComponentCatalog kGemma4Moe26BA4BTarget{
    "gemma4-26b-target", "26B Target", "danmoreng/gemma-4-26B-A4B-it-GEM16",
    "6de2a057f11332420819f8e6efd08e42d7a03bc7", kGemma4Moe26BA4BTargetFiles, false,
    "target"};

inline constexpr std::array kGemma4Moe26BA4BAssistantFiles{
    ModelCatalogFile{".gitattributes", 101ULL, "a0e948ca693c63e0b5139f66bd709003cbcf8bc764acb1ee687a552885c8fe2c", "0fd17d2f7c330afce8bc2b472393143fa66f68a1", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "assistant/.gitattributes"},
    ModelCatalogFile{"LICENSE", 634ULL, "e32c5cdb30142b7c670d61be0f2de18ab0007f72ef131e2869ef51687539c86d", "506ff98349a36c9b78904645c9ae492a9b62e826", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "assistant/LICENSE"},
    ModelCatalogFile{"NOTICE", 791ULL, "555f14e6346372367e5facd6979a9594fd1502f319548933f7c867a1b00ec9d3", "80da8080b8090add2bedb8bec8dc62682b16c88d", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "assistant/NOTICE"},
    ModelCatalogFile{"README.md", 31457ULL, "d93671a2e9b9064f670525925ba085c43b4023e70ec76f29b0c4ea0c9a1f5dcc", "1e883f1f67f7231ac09567790a012a84997293da", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "assistant/README.md"},
    ModelCatalogFile{"chat_template.jinja", 18683ULL, "ae53464bf3be25802b3a5b37def7fd89667067d7577049b3b2d74c4d8de4c6d4", "4741bf6e4132ba23a5537f9d6e74e9a6d613d7cd", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "assistant/chat_template.jinja"},
    ModelCatalogFile{"config.json", 2720ULL, "d3c79600ce09c86c993c89bed7ce05baa376770967ffaa1ac9a0c29347a633e4", "049ec62ef9a48d2f0732b580d90b48cbb0f3616b", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "assistant/config.json"},
    ModelCatalogFile{"gem16.lock.json", 1664ULL, "f2d2278a53ecfb3bf7a093a3207dce70148a88708a51b5050dd8d436c3d69455", "bd555c8d0653bd74ec609bb51720e462174c3545", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "assistant/gem16.lock.json"},
    ModelCatalogFile{"gem16_compilation.json", 217371ULL, "d2a722ccad675807ff73a1a645a0f1fbcc0fc200c402a14e823a5927618a116d", "6e938657610d03a7f30aeec5172849238d8708a0", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "assistant/gem16_compilation.json"},
    ModelCatalogFile{"gem16_model.json", 613ULL, "ef69d5384d6cca061e9941375bb2b18ebc9fee6587e492ef16701dce29b0131e", "f34e42339b16ee761c8724ee21aef629dfd84b65", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "assistant/gem16_model.json"},
    ModelCatalogFile{"generation_config.json", 209ULL, "fb53f4c64e58896a63472e8eb304397db4a39453e1da0f5d57625ec5a8c1050e", "76d3a00538aca6a1b85db3328e1b0f4e93316420", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "assistant/generation_config.json"},
    ModelCatalogFile{"model-00001-of-00001.safetensors", 258317280ULL, "4d3ce2102ad0631d9e7e0586be0b108d5789cbc5b90d21b4c50613979228d927", "4d3ce2102ad0631d9e7e0586be0b108d5789cbc5b90d21b4c50613979228d927", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "assistant/model-00001-of-00001.safetensors"},
    ModelCatalogFile{"model.safetensors.index.json", 8327ULL, "8fcc4b09fb62f710558176406385e9a04423119cd6e81301171d9a64bbfd9165", "c094c640185f76249eb96a10d0d07dd7afd9ec89", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "assistant/model.safetensors.index.json"},
    ModelCatalogFile{"tokenizer.json", 32169440ULL, "75a6583c1a418e2bbd79c60d95d28e0f5bf549ad3f2990b5bdb5238c6c2bf70c", "75a6583c1a418e2bbd79c60d95d28e0f5bf549ad3f2990b5bdb5238c6c2bf70c", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "assistant/tokenizer.json"},
    ModelCatalogFile{"tokenizer_config.json", 3023ULL, "01f2ff1c21ef2e722891380323edcaecd9c86a776aeb9b40148e2f35e3cee4d3", "0672fbe45a4922b10e6ccd13947ecdb166bead28", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "assistant/tokenizer_config.json"},
};
inline constexpr ModelComponentCatalog kGemma4Moe26BA4BAssistant{
    "gemma4-26b-assistant", "26B Assistant", "danmoreng/gemma-4-26B-A4B-it-GEM16",
    "6de2a057f11332420819f8e6efd08e42d7a03bc7", kGemma4Moe26BA4BAssistantFiles, true,
    "assistant"};

inline constexpr std::array kGemma4Moe26BTrellis35TargetFiles{
    ModelCatalogFile{"LICENSE", 634ULL, "e32c5cdb30142b7c670d61be0f2de18ab0007f72ef131e2869ef51687539c86d", "506ff98349a36c9b78904645c9ae492a9b62e826", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "trellis35/LICENSE"},
    ModelCatalogFile{"NOTICE", 243ULL, "f48d72e964adc0c5c616d03a5f6ff2bd973504e8d9ca88559d05e071cff585e7", "7f2511abaa0677ccadfd1a677e84569a2a588470", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "trellis35/NOTICE"},
    ModelCatalogFile{"README.md", 298ULL, "34f25a364f5ba371e5a0230ef77183567763b89ee16155353cd5b6ddadca269a", "53db2bf1ced47c056a83d528612b8b5c0d88cf27", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "trellis35/README.md"},
    ModelCatalogFile{"SHA256SUMS", 754ULL, "958cb982b56f43f53acbd6200d0eb70e9963b3daab1d41d0489f206b6d6daa8e", "93d1ccb225aed94b3f538c8bde9ef49b39d6e05f", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "trellis35/SHA256SUMS"},
    ModelCatalogFile{"chat_template.jinja", 18683ULL, "ae53464bf3be25802b3a5b37def7fd89667067d7577049b3b2d74c4d8de4c6d4", "4741bf6e4132ba23a5537f9d6e74e9a6d613d7cd", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "trellis35/chat_template.jinja"},
    ModelCatalogFile{"config.json", 4152ULL, "8a647d5444c9e77b03bd80ac802683ffdbf64b3d9296ca5257ced8e50349ea16", "ef0ecec886c4ee7fb9151bbd2a4395973e96c061", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "trellis35/config.json"},
    ModelCatalogFile{"gem16.lock.json", 1012ULL, "92ae384611b4b92e061b71a4048abf1f83f54251fd0df612f50751e635fbff08", "26261591a64f018e350c824382beee3726410a46", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "trellis35/gem16.lock.json"},
    ModelCatalogFile{"gem16_compilation.json", 465448ULL, "55181031e34c6214e23a3546a393c5f32acb7e01237133b104f9b02188583204", "5857b4eed5ed4291823d19671bd5ce48008202f8", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "trellis35/gem16_compilation.json"},
    ModelCatalogFile{"gem16_model.json", 996ULL, "0896c371e9458fee1ada61ed4ba9e174ac921d7f02f03969f9a2d38f3fb9840f", "10b7a99cd17cd046524e60bad07f2ff7ddb82968", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "trellis35/gem16_model.json"},
    ModelCatalogFile{"generation_config.json", 203ULL, "b69207f9be617e982d13cc273cce6fd88c98dda99a4bdc5e2d52ffe0a0d9f0a9", "5a376e9fca28bfac73fe81b623bd6e4d00bb0817", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "trellis35/generation_config.json"},
    ModelCatalogFile{"model.gem16", 12204692480ULL, "552ace4b3f2e8e20bbc03a9d4b30887bdb6297d6da9f48d54b4a2b4e9fc803c4", "552ace4b3f2e8e20bbc03a9d4b30887bdb6297d6da9f48d54b4a2b4e9fc803c4", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "trellis35/model.gem16"},
    ModelCatalogFile{"tokenizer.json", 32169626ULL, "cc8d3a0ce36466ccc1278bf987df5f71db1719b9ca6b4118264f45cb627bfe0f", "cc8d3a0ce36466ccc1278bf987df5f71db1719b9ca6b4118264f45cb627bfe0f", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "trellis35/tokenizer.json"},
    ModelCatalogFile{"tokenizer_config.json", 3729ULL, "3ab5c7b94dc97d65ca7064496fa69b88ff875378e1cb7ee3e43070c3a8170999", "bd297dce3d66737f7d6f9136691db3ad05991a2f", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "trellis35/tokenizer_config.json"},
};
inline constexpr ModelComponentCatalog kGemma4Moe26BTrellis35Target{
    "gemma4-26b-trellis35-target", "26B Trellis35 Target", "danmoreng/gemma-4-26B-A4B-it-GEM16",
    "6de2a057f11332420819f8e6efd08e42d7a03bc7", kGemma4Moe26BTrellis35TargetFiles, true,
    "trellis35"};

inline constexpr std::array kGemma4Moe26BVisionFp8Files{
    ModelCatalogFile{"gem16_vision.json", 599ULL, "1de073a0074cebcea26a267376314fe6ecee7c151c3dda1a50fe0a6a0d382b55", "e22264c1aba8cae8af3b75f6059f74ebebb04662", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "vision/gem16_vision.json"},
    ModelCatalogFile{"vision.gem16", 597390648ULL, "805e1fee4ad80dbb76a846c0009d6f57dbb50192e7009ef1633cdc3b5252a536", "805e1fee4ad80dbb76a846c0009d6f57dbb50192e7009ef1633cdc3b5252a536", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "vision/vision.gem16"},
    ModelCatalogFile{"vision.lock.json", 689ULL, "d2bc0fd2105af48dea36a9cbe757e688a8b10ba94bee355047e1f163df01bbc8", "0608adf65eaf6a2f9dffdf8c2adaef68c7a78f41", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "vision/vision.lock.json"},
    ModelCatalogFile{"vision_compilation.json", 456671ULL, "5a13706d89bb3da3d6022207d7741a6754ce6fcedc3d0bb532a72621d4aec94f", "424db2568541fc44e8476aa6cdd3165ce852bc3d", "danmoreng/gemma-4-26B-A4B-it-GEM16", "6de2a057f11332420819f8e6efd08e42d7a03bc7", "vision/vision_compilation.json"},
};
inline constexpr ModelComponentCatalog kGemma4Moe26BVisionFp8{
    "gemma4-26b-vision-fp8", "26B FP8 Vision", "danmoreng/gemma-4-26B-A4B-it-GEM16",
    "6de2a057f11332420819f8e6efd08e42d7a03bc7", kGemma4Moe26BVisionFp8Files, true,
    "vision"};

}  // namespace gem16::studio::generated
