// Generated by tools/generate_native_studio_model_catalog.py. Do not edit.
#pragma once

#include "model_catalog.h"

#include <array>

namespace gem16::studio::generated {

inline constexpr std::array kGemma4Unified12BTargetFiles{
    ModelCatalogFile{".gitattributes", 1570ULL, "34448b82c17d60fec9b65b1f093c115ddbaadc04beb1b0140b6bfed2e012a930", "52373fe24473b1aa44333d318f578ae6bf04b49b", "unsloth/gemma-4-12b-it-NVFP4", "b1f649734b34aa5575b03d186abd1b9be3d0d5c4", ".gitattributes"},
    ModelCatalogFile{"README.md", 29820ULL, "9e2712c56330ea7eefc00a10fd3c37a63364b92e52f10e12266b01a3dc6a9887", "f43dcf66ea657ff11cc683e53122b219bce2e8df", "unsloth/gemma-4-12b-it-NVFP4", "b1f649734b34aa5575b03d186abd1b9be3d0d5c4", "README.md"},
    ModelCatalogFile{"chat_template.jinja", 18924ULL, "845f1ee48e39fc942fe190da9df6a1c5db229e17a96ea08966ad1c9274e73d1b", "e929d662bbbf430219c28133472e0956733a8f84", "unsloth/gemma-4-12b-it-NVFP4", "b1f649734b34aa5575b03d186abd1b9be3d0d5c4", "chat_template.jinja"},
    ModelCatalogFile{"config.json", 7292ULL, "bcc0ec0398a9dd0b09586f835f17c05ed2cce99d958dd59ef629ce77e618ee49", "895577e08537dbce788bdc7a9102bf85bea2e91f", "unsloth/gemma-4-12b-it-NVFP4", "b1f649734b34aa5575b03d186abd1b9be3d0d5c4", "config.json"},
    ModelCatalogFile{"generation_config.json", 255ULL, "801ecff5b38d5a5f5072cd1fb0ee03afabed577fb754518266fea69453acfe6b", "b052ccdb6a742edb72bc98d7d7dd02f0c58e4680", "unsloth/gemma-4-12b-it-NVFP4", "b1f649734b34aa5575b03d186abd1b9be3d0d5c4", "generation_config.json"},
    ModelCatalogFile{"model.safetensors", 9304966064ULL, "7c2ee23298e7c3a9247e8947597dca5a38f8b791a0322487466d2bfad8ce704b", "7c2ee23298e7c3a9247e8947597dca5a38f8b791a0322487466d2bfad8ce704b", "unsloth/gemma-4-12b-it-NVFP4", "b1f649734b34aa5575b03d186abd1b9be3d0d5c4", "model.safetensors"},
    ModelCatalogFile{"processor_config.json", 1382ULL, "6b938e76555b3e9946890770e1abcd442a4718f34041a58e8139dc8ad34545c9", "b889adcd78015bf5a0139438c5fb0b7067529a61", "unsloth/gemma-4-12b-it-NVFP4", "b1f649734b34aa5575b03d186abd1b9be3d0d5c4", "processor_config.json"},
    ModelCatalogFile{"recipe.yaml", 661ULL, "bb19ac4f3bf8c4ffb9b88701bef8faf06c679ae9461751cc849375bb1731c17b", "c27417aceaf0637177e9d44c48ea59ccef873503", "unsloth/gemma-4-12b-it-NVFP4", "b1f649734b34aa5575b03d186abd1b9be3d0d5c4", "recipe.yaml"},
    ModelCatalogFile{"tokenizer.json", 32169726ULL, "adbaa8175acf7609b4359724f40eff359ec4fac1a8647eeb99d4422be708e1cf", "adbaa8175acf7609b4359724f40eff359ec4fac1a8647eeb99d4422be708e1cf", "unsloth/gemma-4-12b-it-NVFP4", "b1f649734b34aa5575b03d186abd1b9be3d0d5c4", "tokenizer.json"},
    ModelCatalogFile{"tokenizer_config.json", 3089ULL, "a62f4e85a47c0c136edaaa3a4f591fd6783717299a9def47e5ad03a49f6a5eb9", "6520cdc25462a5eba96fdac6d8cf3caa461feb35", "google/gemma-4-12B-it", "707f0a3b8a3c7ad586ed01e27eafbad8a27dd0f7", "tokenizer_config.json"},
};
inline constexpr ModelComponentCatalog kGemma4Unified12BTarget{
    "gemma4-12b-target", "12B Target", "unsloth/gemma-4-12b-it-NVFP4",
    "b1f649734b34aa5575b03d186abd1b9be3d0d5c4", kGemma4Unified12BTargetFiles, true};

inline constexpr std::array kGemma4Unified12BAssistantFiles{
    ModelCatalogFile{".gitattributes", 1624ULL, "484fac0cb8b057eefe1992c8b72ac6e7438c7d17bd60c0e278b401c2190f7e72", "602d20f6eefed4b62821062891a7a495e25435f9", "google/gemma-4-12B-it-assistant", "364bd03c9952e5b7da73665ee30c9eccfc408345", ".gitattributes"},
    ModelCatalogFile{"README.md", 29899ULL, "eb9c31937729ee1da6767900f2d3ee79e72f070fdb0181b68983df742abc97d8", "d4d487c449ba880eda5b75718a36a2b65b7ac65b", "google/gemma-4-12B-it-assistant", "364bd03c9952e5b7da73665ee30c9eccfc408345", "README.md"},
    ModelCatalogFile{"config.json", 2346ULL, "b6f19209588fcefe41f65b193fad6148446253c470d36e29441ecc5158a54e6d", "9889070ccf194bd3cab6f61954218a4058696537", "google/gemma-4-12B-it-assistant", "364bd03c9952e5b7da73665ee30c9eccfc408345", "config.json"},
    ModelCatalogFile{"generation_config.json", 233ULL, "02b56bd11e1cd1e363e701a85a2fd7fbaa2992ec3358c1cd7cc44ead7208f505", "6e4ef65e8cf563a9177fd933423f89eed2f74d74", "google/gemma-4-12B-it-assistant", "364bd03c9952e5b7da73665ee30c9eccfc408345", "generation_config.json"},
    ModelCatalogFile{"model.safetensors", 845719296ULL, "3279c173daddd7186e79d652ad94022415736d3a1370625696c898429b06d6df", "3279c173daddd7186e79d652ad94022415736d3a1370625696c898429b06d6df", "google/gemma-4-12B-it-assistant", "364bd03c9952e5b7da73665ee30c9eccfc408345", "model.safetensors"},
    ModelCatalogFile{"tokenizer.json", 32169884ULL, "c001d9ada50af662c94f5ab17ec7e09f6438d1bec8246c47fee6510693d8de35", "c001d9ada50af662c94f5ab17ec7e09f6438d1bec8246c47fee6510693d8de35", "google/gemma-4-12B-it-assistant", "364bd03c9952e5b7da73665ee30c9eccfc408345", "tokenizer.json"},
    ModelCatalogFile{"tokenizer_config.json", 822ULL, "089594a3924fcfd4cb1c596a7906fbf476193519e5198f780912eed02b177e42", "1a6bee041ca75778c514a071efbdb568b0f3d7b0", "google/gemma-4-12B-it-assistant", "364bd03c9952e5b7da73665ee30c9eccfc408345", "tokenizer_config.json"},
};
inline constexpr ModelComponentCatalog kGemma4Unified12BAssistant{
    "gemma4-12b-assistant", "12B Assistant", "google/gemma-4-12B-it-assistant",
    "364bd03c9952e5b7da73665ee30c9eccfc408345", kGemma4Unified12BAssistantFiles, false};

inline constexpr std::array kGemma4Moe26BA4BTargetFiles{
    ModelCatalogFile{".gitattributes", 95ULL, "f15b349b90d515d0af07dc0d7da57e1a3ef9f00a723c70e8bdb8ff7fcb943b83", "c1ad41cbcce50cb9c28dbc5c41f4b17d8ce29f00", "danmoreng/gemma-4-26B-A4B-it-GEM16", "63508b5826527484e707b4b46e2eacf077cf2b35", ".gitattributes"},
    ModelCatalogFile{"LICENSE", 634ULL, "e32c5cdb30142b7c670d61be0f2de18ab0007f72ef131e2869ef51687539c86d", "506ff98349a36c9b78904645c9ae492a9b62e826", "danmoreng/gemma-4-26B-A4B-it-GEM16", "63508b5826527484e707b4b46e2eacf077cf2b35", "LICENSE"},
    ModelCatalogFile{"NOTICE", 778ULL, "e26e0f5e20bc05d54543aae77d45686b614f948e1af7346597e1b4ef533d990b", "a365f24b0c9e70ebfff6128d45fb9f0c62bba3d5", "danmoreng/gemma-4-26B-A4B-it-GEM16", "63508b5826527484e707b4b46e2eacf077cf2b35", "NOTICE"},
    ModelCatalogFile{"README.md", 31418ULL, "7349b325178b75830da550d010c313b2756beb1ebabec5923ba71f108e359a28", "1535491512e42a3ceab0eba250b0810368901ba4", "danmoreng/gemma-4-26B-A4B-it-GEM16", "63508b5826527484e707b4b46e2eacf077cf2b35", "README.md"},
    ModelCatalogFile{"chat_template.jinja", 18683ULL, "ae53464bf3be25802b3a5b37def7fd89667067d7577049b3b2d74c4d8de4c6d4", "4741bf6e4132ba23a5537f9d6e74e9a6d613d7cd", "danmoreng/gemma-4-26B-A4B-it-GEM16", "63508b5826527484e707b4b46e2eacf077cf2b35", "chat_template.jinja"},
    ModelCatalogFile{"config.json", 4152ULL, "8a647d5444c9e77b03bd80ac802683ffdbf64b3d9296ca5257ced8e50349ea16", "ef0ecec886c4ee7fb9151bbd2a4395973e96c061", "danmoreng/gemma-4-26B-A4B-it-GEM16", "63508b5826527484e707b4b46e2eacf077cf2b35", "config.json"},
    ModelCatalogFile{"gem16.lock.json", 4231ULL, "d7d2d30743e7c42aa55537a83f563047c9cbd2d83e0d583a2d2c8bcacbfa51a4", "d2f5aa90480db072e7b3258e16abca22e6bd93cf", "danmoreng/gemma-4-26B-A4B-it-GEM16", "63508b5826527484e707b4b46e2eacf077cf2b35", "gem16.lock.json"},
    ModelCatalogFile{"gem16_compilation.json", 3061406ULL, "7e5e78b9c6f61fbe8829866395634085261e1261a8c783f69affc5a16bd1847a", "fe671accce31db603d8d139bcef8523ee3baac34", "danmoreng/gemma-4-26B-A4B-it-GEM16", "63508b5826527484e707b4b46e2eacf077cf2b35", "gem16_compilation.json"},
    ModelCatalogFile{"gem16_model.json", 671ULL, "c1015228120105ff5e54efe300c77c7e6a831ed598425f4f4c1b27c673732049", "02cf4afbfe3051e630eecd85c313fbb2a11ef015", "danmoreng/gemma-4-26B-A4B-it-GEM16", "63508b5826527484e707b4b46e2eacf077cf2b35", "gem16_model.json"},
    ModelCatalogFile{"generation_config.json", 203ULL, "b69207f9be617e982d13cc273cce6fd88c98dda99a4bdc5e2d52ffe0a0d9f0a9", "5a376e9fca28bfac73fe81b623bd6e4d00bb0817", "danmoreng/gemma-4-26B-A4B-it-GEM16", "63508b5826527484e707b4b46e2eacf077cf2b35", "generation_config.json"},
    ModelCatalogFile{"model.gem16", 14696668160ULL, "1ed73cf105b68db937ac0992283d31fdb2225474204341440721f41fe871bb72", "1ed73cf105b68db937ac0992283d31fdb2225474204341440721f41fe871bb72", "danmoreng/gemma-4-26B-A4B-it-GEM16", "63508b5826527484e707b4b46e2eacf077cf2b35", "model.gem16"},
    ModelCatalogFile{"tokenizer.json", 32169626ULL, "cc8d3a0ce36466ccc1278bf987df5f71db1719b9ca6b4118264f45cb627bfe0f", "cc8d3a0ce36466ccc1278bf987df5f71db1719b9ca6b4118264f45cb627bfe0f", "danmoreng/gemma-4-26B-A4B-it-GEM16", "63508b5826527484e707b4b46e2eacf077cf2b35", "tokenizer.json"},
    ModelCatalogFile{"tokenizer_config.json", 3729ULL, "3ab5c7b94dc97d65ca7064496fa69b88ff875378e1cb7ee3e43070c3a8170999", "bd297dce3d66737f7d6f9136691db3ad05991a2f", "danmoreng/gemma-4-26B-A4B-it-GEM16", "63508b5826527484e707b4b46e2eacf077cf2b35", "tokenizer_config.json"},
};
inline constexpr ModelComponentCatalog kGemma4Moe26BA4BTarget{
    "gemma4-26b-target", "26B Target", "danmoreng/gemma-4-26B-A4B-it-GEM16",
    "63508b5826527484e707b4b46e2eacf077cf2b35", kGemma4Moe26BA4BTargetFiles, false};

inline constexpr std::array kGemma4Moe26BA4BAssistantFiles{
    ModelCatalogFile{".gitattributes", 101ULL, "a0e948ca693c63e0b5139f66bd709003cbcf8bc764acb1ee687a552885c8fe2c", "0fd17d2f7c330afce8bc2b472393143fa66f68a1", "danmoreng/gemma-4-26B-A4B-it-assistant-GEM16", "466cc26d157fad0cc946f094ae904445147c38b4", ".gitattributes"},
    ModelCatalogFile{"LICENSE", 634ULL, "e32c5cdb30142b7c670d61be0f2de18ab0007f72ef131e2869ef51687539c86d", "506ff98349a36c9b78904645c9ae492a9b62e826", "danmoreng/gemma-4-26B-A4B-it-assistant-GEM16", "466cc26d157fad0cc946f094ae904445147c38b4", "LICENSE"},
    ModelCatalogFile{"NOTICE", 791ULL, "555f14e6346372367e5facd6979a9594fd1502f319548933f7c867a1b00ec9d3", "80da8080b8090add2bedb8bec8dc62682b16c88d", "danmoreng/gemma-4-26B-A4B-it-assistant-GEM16", "466cc26d157fad0cc946f094ae904445147c38b4", "NOTICE"},
    ModelCatalogFile{"README.md", 31457ULL, "d93671a2e9b9064f670525925ba085c43b4023e70ec76f29b0c4ea0c9a1f5dcc", "1e883f1f67f7231ac09567790a012a84997293da", "danmoreng/gemma-4-26B-A4B-it-assistant-GEM16", "466cc26d157fad0cc946f094ae904445147c38b4", "README.md"},
    ModelCatalogFile{"chat_template.jinja", 18683ULL, "ae53464bf3be25802b3a5b37def7fd89667067d7577049b3b2d74c4d8de4c6d4", "4741bf6e4132ba23a5537f9d6e74e9a6d613d7cd", "danmoreng/gemma-4-26B-A4B-it-assistant-GEM16", "466cc26d157fad0cc946f094ae904445147c38b4", "chat_template.jinja"},
    ModelCatalogFile{"config.json", 2720ULL, "d3c79600ce09c86c993c89bed7ce05baa376770967ffaa1ac9a0c29347a633e4", "049ec62ef9a48d2f0732b580d90b48cbb0f3616b", "danmoreng/gemma-4-26B-A4B-it-assistant-GEM16", "466cc26d157fad0cc946f094ae904445147c38b4", "config.json"},
    ModelCatalogFile{"gem16.lock.json", 1664ULL, "f2d2278a53ecfb3bf7a093a3207dce70148a88708a51b5050dd8d436c3d69455", "bd555c8d0653bd74ec609bb51720e462174c3545", "danmoreng/gemma-4-26B-A4B-it-assistant-GEM16", "466cc26d157fad0cc946f094ae904445147c38b4", "gem16.lock.json"},
    ModelCatalogFile{"gem16_compilation.json", 217371ULL, "d2a722ccad675807ff73a1a645a0f1fbcc0fc200c402a14e823a5927618a116d", "6e938657610d03a7f30aeec5172849238d8708a0", "danmoreng/gemma-4-26B-A4B-it-assistant-GEM16", "466cc26d157fad0cc946f094ae904445147c38b4", "gem16_compilation.json"},
    ModelCatalogFile{"gem16_model.json", 613ULL, "ef69d5384d6cca061e9941375bb2b18ebc9fee6587e492ef16701dce29b0131e", "f34e42339b16ee761c8724ee21aef629dfd84b65", "danmoreng/gemma-4-26B-A4B-it-assistant-GEM16", "466cc26d157fad0cc946f094ae904445147c38b4", "gem16_model.json"},
    ModelCatalogFile{"generation_config.json", 209ULL, "fb53f4c64e58896a63472e8eb304397db4a39453e1da0f5d57625ec5a8c1050e", "76d3a00538aca6a1b85db3328e1b0f4e93316420", "danmoreng/gemma-4-26B-A4B-it-assistant-GEM16", "466cc26d157fad0cc946f094ae904445147c38b4", "generation_config.json"},
    ModelCatalogFile{"model-00001-of-00001.safetensors", 258317280ULL, "4d3ce2102ad0631d9e7e0586be0b108d5789cbc5b90d21b4c50613979228d927", "4d3ce2102ad0631d9e7e0586be0b108d5789cbc5b90d21b4c50613979228d927", "danmoreng/gemma-4-26B-A4B-it-assistant-GEM16", "466cc26d157fad0cc946f094ae904445147c38b4", "model-00001-of-00001.safetensors"},
    ModelCatalogFile{"model.safetensors.index.json", 8327ULL, "8fcc4b09fb62f710558176406385e9a04423119cd6e81301171d9a64bbfd9165", "c094c640185f76249eb96a10d0d07dd7afd9ec89", "danmoreng/gemma-4-26B-A4B-it-assistant-GEM16", "466cc26d157fad0cc946f094ae904445147c38b4", "model.safetensors.index.json"},
    ModelCatalogFile{"tokenizer.json", 32169440ULL, "75a6583c1a418e2bbd79c60d95d28e0f5bf549ad3f2990b5bdb5238c6c2bf70c", "75a6583c1a418e2bbd79c60d95d28e0f5bf549ad3f2990b5bdb5238c6c2bf70c", "danmoreng/gemma-4-26B-A4B-it-assistant-GEM16", "466cc26d157fad0cc946f094ae904445147c38b4", "tokenizer.json"},
    ModelCatalogFile{"tokenizer_config.json", 3023ULL, "01f2ff1c21ef2e722891380323edcaecd9c86a776aeb9b40148e2f35e3cee4d3", "0672fbe45a4922b10e6ccd13947ecdb166bead28", "danmoreng/gemma-4-26B-A4B-it-assistant-GEM16", "466cc26d157fad0cc946f094ae904445147c38b4", "tokenizer_config.json"},
};
inline constexpr ModelComponentCatalog kGemma4Moe26BA4BAssistant{
    "gemma4-26b-assistant", "26B Assistant", "danmoreng/gemma-4-26B-A4B-it-assistant-GEM16",
    "466cc26d157fad0cc946f094ae904445147c38b4", kGemma4Moe26BA4BAssistantFiles, false};

}  // namespace gem16::studio::generated
