#!/usr/bin/env python3
"""Rasterize the canonical gem16 SVG and embed it for native GPU backends."""

from __future__ import annotations

import argparse
import subprocess
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("destination", type=Path)
    parser.add_argument("--size", type=int, default=256)
    args = parser.parse_args()
    if args.size < 16 or args.size > 1024:
        parser.error("--size must be between 16 and 1024")

    png = subprocess.run(
        [
            "rsvg-convert",
            "--width",
            str(args.size),
            "--height",
            str(args.size),
            str(args.source),
        ],
        check=True,
        stdout=subprocess.PIPE,
    ).stdout
    rows = []
    for offset in range(0, len(png), 12):
        rows.append(
            "    " + ", ".join(f"0x{value:02x}" for value in png[offset : offset + 12])
        )
    rendered = "\n".join(
        [
            "// Generated by nativeStudio/tools/generate_logo_header.py from",
            "// docs/gem16_logo.svg. Do not edit by hand.",
            "#pragma once",
            "",
            "#include <cstddef>",
            "#include <cstdint>",
            "",
            "namespace gem16::studio {",
            "",
            "inline constexpr std::uint8_t kGem16LogoPng[] = {",
            *(f"{row}," for row in rows),
            "};",
            "inline constexpr std::size_t kGem16LogoPngSize = sizeof(kGem16LogoPng);",
            "",
            "}  // namespace gem16::studio",
            "",
        ]
    )
    args.destination.parent.mkdir(parents=True, exist_ok=True)
    args.destination.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
