function(gem16gb_set_project_warnings target)
  if(MSVC)
    # nvcc-generated host stubs can emit MSVC warnings such as C4211. Keep
    # warnings-as-errors on project C++ sources without applying /WX to code
    # generated by the CUDA toolchain.
    target_compile_options(${target} PRIVATE
      $<$<COMPILE_LANGUAGE:CXX>:/W4>
      $<$<AND:$<COMPILE_LANGUAGE:CXX>,$<BOOL:${GEM16GB_WARNINGS_AS_ERRORS}>>:/WX>
      $<$<COMPILE_LANGUAGE:CUDA>:-Xcompiler=/W4>
    )
  else()
    target_compile_options(${target} PRIVATE
      $<$<COMPILE_LANGUAGE:CXX>:-Wall;-Wextra;-Wpedantic;-Wconversion;-Wshadow;-Wformat=2;-Wundef>
      $<$<AND:$<COMPILE_LANGUAGE:CXX>,$<BOOL:${GEM16GB_WARNINGS_AS_ERRORS}>>:-Werror>
    )
  endif()
  target_compile_options(${target} PRIVATE $<$<COMPILE_LANGUAGE:CUDA>:--expt-relaxed-constexpr>)
endfunction()

